FROM ubuntu:20.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    mono-runtime \
    libmono-system-windows-forms4.0-cil \
    x11-apps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY MouseTracker.exe /app/
ENV DISPLAY=:0
CMD ["mono", "MouseTracker.exe"]
